Gael trial
wiringbits/scala-webapp-template pull request #20
Opened 2021-07-12 21:05 UTC by elgael06

2021-07-12 21:59 UTC, AlexITC requested changes
Overall, looks good, just remove the useless files (`.metals/*`/`*.iml`)

2021-07-12 21:59 UTC, AlexITC commented on web/src/main/scala/net/wiringbits/components/widgets/SignInForm.scala
>      // TODO: Use a form to get the enter key submitting the form
This comment does not apply anymore, remove it

2021-07-12 21:59 UTC, AlexITC commented on web/src/main/scala/net/wiringbits/components/widgets/SignInForm.scala
> +        //.onClick(_ => doLogin())
Remove unused code

2021-07-12 21:59 UTC, AlexITC commented on web/src/main/scala/net/wiringbits/components/widgets/SignInForm.scala
>      mui
This seems to have wrong alignment, which reminds me to enable scalafmt check in circleci

2021-07-13 00:19 UTC, elgael06 commented
Use form: submit event  enter key

2021-07-13 23:47 UTC, elgael06 commented
remove the useless files (.metals/*/*.iml)

2021-07-13 23:55 UTC, AlexITC approved these changes

2021-07-13 23:55 UTC, merged